remote_theme: fongandrew/hydeout
lang: ja
title: '志賀 慶一 Keiichi Shiga'
description: 'Keiichi Shiga GitHub Pages, English Blog and Links. 志賀 慶一 (Keiichi Shiga) from Japan'
url: https://keiichi.github.io
baseurl: ''
paginate: 5
excerpt_separator: '<!--more-->'

sidebar_home_link: true
#sidebar_blog_link: 

sidebar:
  title: '志賀 慶一 <br>Keiichi Shiga'

author:
  name: ' 志賀 慶一 Keiichi Shiga'
  url: https://facebook.com/keiichishiga

markdown:  kramdown
highlighter: rouge

permalink: "/:year/:month/:title/"
defaults:
  - scope:
      path: ""
    values:
      image: /ogp.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
